services:
  google-drive-ocamlfuse:
    container_name: google-drive-ocamlfuse
    image:  rennsport/google-drive-ocamlfuse:0.7.32 # tag in sync with google-drive-ocamlfuse release number; starts at 0.7.32
    restart: always
    environment:
      # Leave CLIENT_ID, CLIENT_SECRET, VERIFICATION_CODE, and TEAM_DRIVE_ID commented out after first run
      #CLIENT_ID: "YOUR_CLIENT_ID"
      #CLIENT_SECRET: "YOUR_CLIENT_SECRET"
      #VERIFICATION_CODE: "YOUR_VERIFICATION_CODE"
      #TEAM_DRIVE_ID: "ADD_IF_NEEDED"
      MOUNT_OPTS: "nonempty,allow_other"
    security_opt:
      - "apparmor:unconfined"
    cap_add:
      - "mknod"
      - "sys_admin"
    devices:
      - "/dev/fuse"
    volumes:
      - "./google-drive-ocamlfuse_local_data:/mnt/gdrive:shared"
      - "./google-drive-ocamlfuse_local_config:/config/.gdfuse/default"
